name: Build & Deploy
on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Hugo (extended)
        run: |
          HUGO_VERSION=0.127.0
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz -O hugo.tar.gz
          tar -xzf hugo.tar.gz
          sudo mv hugo /usr/local/bin/hugo
          hugo version
      - name: Build
        run: hugo --minify
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public
          server-dir: ${{ secrets.FTP_PATH }}
          dangerous-clean-slate: true
